### ISSUE TITLE
Option to not restore scroll position on sites that dynamically change content

### ISSUE THREAD

**Issue by ptr727** [greatsuspender/thegreatsuspender#1062]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.0
 * Browser name & version: Google Chrome 78.0.3904.87 (Official Build) (64-bit)
 * Operating system & version: Win10 1809

Whenever a tab on a site like facebook, twitter, or reddit is restored, and the scroll position is restored, the content refreshed, and I have to manually scroll back to the top of the page, as the the restored scroll position is in the middle of new content.

Please add an option to disable the scroll position restoration logic, or detect when a page is dynamic, and do not try to restore the scroll position.

**Comment by DFNCTSC** [comment]
+1 for "Please add an option to disable the scroll position restoration logic".

`gsScrollPos` is probably the biggest bug culprit in the entire extension and definitely the largest bloat vector.

I would have no problem with this "feature" being removed because it's not correctly implemented in a way that manages itself properly without issues down-the-line.

**Comment by ptr727** [comment]
Abandon in favor of Chrome's native tab suspending capabilities.
