### ISSUE TITLE
the great suspender is more stable with --single-process

### ISSUE THREAD

**Issue by ohsix** [greatsuspender/thegreatsuspender#665]
filing so i don't forget!

in a large browser session (500-1000 tabs, multiple windows) the great suspender tends to stop responding, and chrome kills it; and that repeats until it stops responding, but chrome doesn't kill it

well, with the same session and --single-process, the great suspender seems bulletproof

to me that speaks to ipc overhead/throttling/just plain not keeping up between threads, but i don't know anything about chrome

hope this isn't too rude ;]

**Comment by CollinChaffin** [comment]
LOL not rude but before posting things like this you may want to take exactly 30 seconds to research what you are doing:
````
https://www.chromium.org/developers/design-documents/process-models
````

Which very clearly states by those that by your own admission, DO know about Chrome (they wrote it):
````
"It is not a safe or robust architecture, as any renderer crash will cause the loss of the entire browser process. It is designed for testing and development purposes, and it may contain bugs that are not present in the other architectures."
````
So you are not only running your browser in a very unstable mode never meant for end-users, but you're posting on a 3rd party app that uses that browser how great it is to do so for it's other users to see and potentially attempt.  The only reason this APPEARS to give you a sense of stability is that you are smashing ALL of Chrome's plugins and other MANY processes into a single bucket and just because you win mini lotteries from time to time and it doesn't CRASH is absurd.  I run under the normal, fully supported multi-process (default) and can screenshot 381 open tabs right now spread over 31 different windows that has been a running session for many days - and I run Great Suspender and also do not crash, so my guess is this switch is more an indicator of other possible stability issues ON YOUR MACHINE which I would recommend you make your new focus.

This is also a nice way of saying to anyone else that read this open issue title and are considering trying it:  
# DON'T DO THAT.

**Comment by ForsakenHarmony** [comment]
sorry but I highly doubt you can even use that many tabs at once, you should really think about getting a tab manager, i.e. "tabs outliner"

**Comment by deanoemcke** [comment]
I will close this as there is no real resolution. But feel free to create a new issue to address the 'extension stops responding after x tabs open'.

**Comment by ohsix** [comment]
i will, thanks; just had to write it down somewhere to note it, not sure if i'll ever have the time to find a real root cause

**Comment by ohsix** [comment]
@CollinChaffin good one. you seemed to have ignored that i pointed out an ipc bottleneck, the number of processes is not relevant; chrome merges processes in compartments and you end up with a random set anyways. the issue is that in the worst case situation where every tab is loading the extension pages, something stops communicating. this is not a crash, the crash comes later when the message loop for the extension process stops responding, because of an ipc problem

this also isn't a case of the extension process getting swapped out, or any data it touches; there is a definitive bug, either in chrome or the extension (though, looking at chrome) the issue is placing it in either bin

ipc mechanisms have queues and rate limiting so you can't just end up denying service from legitimate clients with programming bugs. by extension, you could say DON'T DO THAT to the hypothetical broken extension that is posting 10000 messages a second, where 5 would do, or where someone typo'd a number and that's just what happened when a timeout was wrong

the conceit of the original note is that systems that communicate with ipc tend to do this, and it is typical; the result is presumed undesirable. consequently, when you do something like --single-process and you get a significantly different outcome, again based on what happens with ipc (the inter part is smaller) it is notable. i didn't want to forget the observation

**Comment by ohsix** [comment]
found a bit smaller area to look when i get a chance, it's in the code that scans older sessions and reinserts them into indexdb after a crash

**Comment by CollinChaffin** [comment]
...and your bicycle is more stable if you bolt on the training wheels....and then walk/push it backwards, instead of getting on and riding it. :)

Again - read what the DEVELOPERS OF CHROME wrote about the single process setting - they wrote the code for that setting for TESTING, IT IS NOT STABLE, AND NOT INTENDED FOR ACTUAL BROWSER USE.  In other words, stop walking your bicycle backwards and get on and try riding it. :)

**Comment by ohsix** [comment]
@CollinChaffin you're getting really excited over something that's not relevant

the actual problem is kind of a bummer, it's in the shared buffer handling stuff in chrome (maybe resource/handle exhaustion? it's a lot of work for the chrome-unfamiliar to track down)

TGS just happens to be the one creating lots of shared resources used with the gpu renderer (because it is in so many tabs) and there's an eventual failure in ContextResult CommandBufferProxyImpl::Initialize https://chromium.googlesource.com/chromium/src/gpu/+/master/ipc/client/command_buffer_proxy_impl.cc ->   shared_state_shm_ = AllocateAndMapSharedMemory(sizeof(*shared_state()));

the TGS process then aborts, and chrome has a bad time after

what TGS seemed to be doing at the time was a red herring, and i can avoid that allocation failure with --disable-gpu --disable-software-rasterizer

**Comment by deanoemcke** [comment]
@ohsix i'm not sure where to go from here. is there something concrete I can do to resolve this issue? what are the factors that contribute towards this failure? is it purely the number of suspended tabs open? or is there some way I can reduce the amount of resources each suspended tab uses?

**Comment by ohsix** [comment]
i don't think so

if there's a clear thing to fix, the circumstances that it's actually happening in is pretty absurd and maybe not worth it

if i had one website open in as many tabs as tgs is, as an extension, it would probably have the same problem somewhere else

since it seems to not happen with the gpu off, it could very well be the intel gpu driver, even with a modest amount of pages per-context for gpu stuff. it adds up when you have thousands of them (like stack sizes with threads)
